### ISSUE TITLE
Module "crypto" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by ajnsn** [littlefoxcompany/usemods#105]
fyi: Since v1.51 using a Vite build

vite v5.3.1 building for production...
[plugin:vite:resolve] [plugin vite:resolve] Module "crypto" has been externalized for browser compatibility, imported by "/node_modules/usemods/dist/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

<sub><a href="https://huly.app/guest/littlefox?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2Njc3Y2FlMWExNDU4ZjI0Y2Q3NjkxYzUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctamVyZW15LWxpdHRsZWZveC02NjZiNzNiYi1iYjhmMmZiOWJiLWVkMTM5ZSIsInByb2R1Y3RJZCI6IiJ9.VU6OTAniBGen6QEqJy9lblyga-7xA8Ce7yey6kOkQKE">Huly&reg;: <b>MODS-103</b></a></sub>

**Comment by jrmymbtlr** [comment]
Hi @ajnsn!

Thanks for pointing this one out.

I've made a fix in v1.5.2 that uses globalThis for Node 19+, which removes the need to import the Crypto library. There's also a gracefully fallback for older Node versions when performing random functions in SSR environments.

Client-side remains the same!

https://github.com/littlefoxcompany/usemods/releases/tag/v1.5.2

**Comment by ajnsn** [comment]
Thank you so much @jrmymbtlr - I can confirm that 1.52 resolves this  👍
