### ISSUE TITLE
Provide a License 📝 

### ISSUE THREAD

**Issue by DennisSmuda** [LittleFoxCompany/usemods#75]
Hey Guys, I just stumbled upon this - amazing work!

I hate to be *that* guy, but do you have any plans on Licensing 🙈 

I'd love to see MIT on this! Cheers ❤️

**Comment by jrmymbtlr** [comment]
Ah amazing catch, we covered the packages under MIT but not the full project. I've now included the MIT licence #79 just in time for the pending 1.0.0 release.
