### ISSUE TITLE
User agent parser

### ISSUE THREAD

**Issue by alexcroox** [LittleFoxCompany/usemods#95]
Since there are functions for detecting the browser and machine I wondered if you could utilise similar logic to provide a userAgent string parser to return everything parsed as an object?

Thanks!

**Comment by jrmymbtlr** [comment]
I think you'll like what's in the next update (#89)! We've included a stack of new device functions, including a function to push these into your body classes.

Includes a Tailwind plugin for now `ios:` `android:` `safari:` etc variables.

![CleanShot 2024-05-30 at 09 38 21@2x](https://github.com/LittleFoxCompany/usemods/assets/24998792/fcefb968-7d63-4976-b9df-c1227e5020df)

![image](https://github.com/LittleFoxCompany/usemods/assets/24998792/366284b2-0749-44d7-9386-21b47e97a41d)

**Comment by alexcroox** [comment]
That sounds great thanks! Ideally it could optionally accept a user agent string param so it could be called server side. Thanks!
